export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

export const ITEM_EQUIP_REQUEST = "ITEM_EQUIP_REQUEST";
export const ITEM_EQUIP_SUCCESS = "ITEM_EQUIP_SUCCESS";
export const ITEM_EQUIP_FAILURE = "ITEM_EQUIP_FAILURE";

export const ITEM_BUY_REQUEST = "ITEM_BUY_REQUEST";
export const ITEM_BUY_SUCCESS = "ITEM_BUY_SUCCESS";
export const ITEM_BUY_FAILURE = "ITEM_BUY_FAILURE";

export const ITEM_SELL_REQUEST = "ITEM_SELL_REQUEST";
export const ITEM_SELL_SUCCESS = "ITEM_SELL_SUCCESS";
export const ITEM_SELL_FAILURE = "ITEM_SELL_FAILURE";
